/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-11 14:31:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.PORTFOLIO.team.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>ì¤ìµ-ëìì ì½ ë² ì´ì¤</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/master.css\" />\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<input id=\"toggle_menu\" type=\"checkbox\" />\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\t<!--ë°ë¡ê°ê¸°ë©ë´-->\r\n");
      out.write("\t<div class=\"skip\">\r\n");
      out.write("\t\t<a href=\"#contents_wrap\">ë³¸ë¬¸ ë°ë¡ê°ê¸°</a>\r\n");
      out.write("\t\t<a href=\"#main_nav\">ë©ì¸ë©ë´ ë°ë¡ê°ê¸°</a>\r\n");
      out.write(" \t\t<a href=\"#main_footer\">í¸í° ë°ë¡ê°ê¸°</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<!--pcì©, ì¤í¬ë¡¤ ë´ë ¸ì ë ëíëë ë©ì¸ë©ë´-->\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("\t\t\tsetInterval(function(){\r\n");
      out.write("\t\t\t\tif($(window\t).scrollTop()>=110){\r\n");
      out.write("\t\t\t\t\t$(\"#main_nav\").animate({top:0},500);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#main_nav\").animate({top:-80},500);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("    </script>\r\n");
      out.write("\t<nav id=\"main_nav\">\r\n");
      out.write("    \t<h2 class=\"blind\">ë©ì¸ë©ë´</h2>\r\n");
      out.write("    \t<ul>\r\n");
      out.write("        \t<li><a href=\"#\">ëìì ì½</a></li>\r\n");
      out.write("        \t<li><a href=\"#\"><span style=\"border-bottom: 2px solid #FC3\">ì íìê°</span></a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì íê°ë°</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì¬íê³µí</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ê³ ê°ì§ì</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">íë³´</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì¬ì´ë²ê°ì¬ì¤</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("\t<!--í¤ë : í ê¸ë©ë´, ë¡ê³ , í ê¸ê²ì-->\r\n");
      out.write("\t<header id=\"main_header\">\r\n");
      out.write("    \t<label class=\"toggle_menu\" for=\"toggle_menu\"></label>\r\n");
      out.write("        <h1 id=\"logo\"><a href=\"index.html\">ëìì ì½</a></h1>\r\n");
      out.write("        <nav id=\"top_nav\">\r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li>\r\n");
      out.write("                \t<label class=\"search\" for=\"search\"></label>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"lang_wrap\">\r\n");
      out.write("                \t<a href=\"#\">KO</a>\r\n");
      out.write("                    <span>&#124;</span>\r\n");
      out.write("                    <a href=\"#\">EN</a>\r\n");
      out.write("               \t</li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("\t<!--ê²ìí ê¸ í´ë¦­ì ê²ìì°½-->\r\n");
      out.write("    <input id=\"search\" type=\"checkbox\"/>\r\n");
      out.write("    <div class=\"search_wrap\">\r\n");
      out.write("    \t<form>\r\n");
      out.write("        \t<label class=\"btn_close\" for=\"search\"></label>\r\n");
      out.write("        \t<fieldset>\r\n");
      out.write("            \t<input type=\"text\" class=\"text\" placeholder=\"ê²ìì´ë¥¼ ìë ¥íì¸ì.\"/>\r\n");
      out.write("                <input type=\"image\" class=\"btn_search\" src=\"images/btn_search.png\" alt=\"ê²ì\"/>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<!--ë©ë´í ê¸ í´ë¦­ì í ê¸ë©ë´-->\r\n");
      out.write("    <div id=\"toggle_nav_wrap\">\r\n");
      out.write("    \t<h2 class=\"blind\">ë©ì¸ë©ë´</h2>\r\n");
      out.write("        <label class=\"menu_close\" for=\"toggle_menu\"></label>\r\n");
      out.write("        <ul id=\"toggle_nav\">\r\n");
      out.write("        \t<li><a href=\"#\">ëìì ì½</a></li>\r\n");
      out.write("        \t<li><a href=\"sub.html\"><span style=\"border-bottom: 2px solid #FC3\">ì íìê°</span></a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì íê°ë°</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì¬íê³µí</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ê³ ê°ì§ì</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">íë³´</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">ì¬ì´ë²ê°ì¬ì¤</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div id=\"lang\">\r\n");
      out.write("            <a href=\"#\">KO</a>\r\n");
      out.write("            <span>&#124;</span>\r\n");
      out.write("            <a href=\"#\">EN</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <label class=\"menu_bg_close\" for=\"toggle_menu\"></label>\r\n");
      out.write("   </div><!--/toggle_nav-->\r\n");
      out.write("   \r\n");
      out.write("  <div id=\"contents_wrap\">\r\n");
      out.write("  \tìë¸íì´ì§ ë´ì©\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\t<!--í¸í° ìì­-->   \r\n");
      out.write("   <footer id=\"main_footer\">\r\n");
      out.write("\t\t<div id=\"family_site\">\r\n");
      out.write("        \t<h3 class=\"f_title\">Family Site </h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ì§ì£¼íì¬</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ëìììì¤íë©ì¤</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ììë£</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ëìì¤ì¸ ì¹´</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">ëì²ì</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ì ì½</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ëìST</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">ëìì ì½</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">ìì¤í°í</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">DMB</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ë¬¼ë¥</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ì©ë§ë¡ì§ì¤</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ë³ì ë¦¬</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ìì</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ê¸°ê³ë¶í</dt>\r\n");
      out.write("                        <dd><a href=\"#\">íêµ­ì ëê³µì</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ì ë³´íµì </dt>\r\n");
      out.write("                        <dd><a href=\"#\">DAì¸í¬ë©ì´ì</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>ê±´ì¤</dt>\r\n");
      out.write("                        <dd><a href=\"#\">ì² ê·¼ì¢í©ê±´ì¤</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>í´ì¸</dt>\r\n");
      out.write("                        <dd><a href=\"#\">Dong-A America Co.</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">ìì£¼ëììë£ì íê³µì¬</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">Dong-A Participacoes Ltda</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div> \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"brand_site\">\r\n");
      out.write("        \t<h3 class=\"f_title\">Brand Site</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">ê°ê·¸ë¦°</a></li>\r\n");
      out.write("                <li><a href=\"#\">ë°ì¹´ì¤</a></li>\r\n");
      out.write("                <li><a href=\"#\">ëª¨ëì¼ì´</a></li>\r\n");
      out.write("                <li><a href=\"#\">ì¨íë</a></li>\r\n");
      out.write("                <li><a href=\"#\">íí¬</a></li>\r\n");
      out.write("                <li><a href=\"#\">ë¹ê²í¬ë¦¼í¤</a></li>\r\n");
      out.write("                <li><a href=\"#\">êµ­í ëì¥ì </a></li>\r\n");
      out.write("                <li><a href=\"#\">íê²½ìëªêµì¤</a></li>\r\n");
      out.write("                <li><a href=\"#\">AD CAFE</a></li>\r\n");
      out.write("            </ul>            \r\n");
      out.write("        </div>  \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"policy\">\r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li><a href=\"#\">ê°ì¸ì ë³´ì·¨ê¸ë°©ì¹¨</a></li>\r\n");
      out.write("                <li class=\"last\"><a href=\"#\">ì¸ì¬ê°ë°ì</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"f_address\">\r\n");
      out.write("            <h1 id=\"f_logo\"><img src=\"images/logo_footer.png\" alt=\"ëìì ì½ ë¡ê³ \"/></h1>\r\n");
      out.write("            <address>\r\n");
      out.write("                <p>ìì¸ì ëëë¬¸êµ¬ ì²í¸ëë¡ 64 TEL.02 - 920 - 8112</p>\r\n");
      out.write("                <p class=\"copyright\">Copytight DONG-A PHARM. All rights reserved </p>\r\n");
      out.write("            </address>\r\n");
      out.write("            <div id=\"wa\"><a href=\"#\"><img src=\"images/award.jpg\" alt=\"WEB AWARD\"/></a></div>\r\n");
      out.write("   </footer>\r\n");
      out.write("    \r\n");
      out.write("</div><!--/wrap-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
