/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-12 08:18:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.PORTFOLIO.team.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>SIST 렌트카</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/master.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/contentsStyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/mainSection.css\" />\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-2.1.4.js\"></script>\r\n");
      out.write("<script src=\"js/modernizr.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"CSS/bootstrap.min.css\" />\r\n");
      out.write("<!-- Custom stlylesheet -->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"CSS/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<input id=\"toggle_menu\" type=\"checkbox\" />\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\t<!--바로가기메뉴-->\r\n");
      out.write("\t<div class=\"skip\">\r\n");
      out.write("\t\t<a href=\"#contents_wrap\">본문 바로가기</a>\r\n");
      out.write("\t\t<a href=\"#main_nav\">메인메뉴 바로가기</a>\r\n");
      out.write(" \t\t<a href=\"#main_footer\">푸터 바로가기</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<!--pc용, 스크롤 내렸을 때 나타나는 메인메뉴-->\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("\t\t\tsetInterval(function(){\r\n");
      out.write("\t\t\t\tif($(window\t).scrollTop()>=110){\r\n");
      out.write("\t\t\t\t\t$(\"#main_nav\").animate({top:0},500);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#main_nav\").animate({top:-80},500);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("    </script>\r\n");
      out.write("\t<nav id=\"main_nav\">\r\n");
      out.write("    \t<h2 class=\"blind\">메인메뉴</h2>\r\n");
      out.write("    \t<ul>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("\t<!--헤더 : 토글메뉴, 로고, 토글검색-->\r\n");
      out.write("\t<header id=\"main_header\">\r\n");
      out.write("    \t<label class=\"toggle_menu\" for=\"toggle_menu\"></label>\r\n");
      out.write("        <h1 id=\"logo\"><a href=\"index.html\">SIST렌트카</a></h1>\r\n");
      out.write("        <nav id=\"top_nav\">\r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li>\r\n");
      out.write("                \t<label class=\"search\" for=\"search\"></label>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"lang_wrap\">\r\n");
      out.write("                \t<a href=\"#\">LIGIN</a>\r\n");
      out.write("                    <span>&#124;</span>\r\n");
      out.write("                    <a href=\"#\">JOIN</a>\r\n");
      out.write("               \t</li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("\t<!--검색토글 클릭시 검색창-->\r\n");
      out.write("    <input id=\"search\" type=\"checkbox\"/>\r\n");
      out.write("    <div class=\"search_wrap\">\r\n");
      out.write("    \t<form>\r\n");
      out.write("        \t<label class=\"btn_close\" for=\"search\"></label>\r\n");
      out.write("        \t<fieldset>\r\n");
      out.write("            \t<input type=\"text\" class=\"text\" placeholder=\"검색어를 입력하세요.\"/>\r\n");
      out.write("                <input type=\"image\" class=\"btn_search\" src=\"images/btn_search.png\" alt=\"검색\"/>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<!--메뉴토글 클릭시 토글메뉴-->\r\n");
      out.write("    <div id=\"toggle_nav_wrap\">\r\n");
      out.write("    \t<h2 class=\"blind\">메인메뉴</h2>\r\n");
      out.write("        <label class=\"menu_close\" for=\"toggle_menu\"></label>\r\n");
      out.write("        <ul id=\"toggle_nav\">\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"sub.html\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        \t<li><a href=\"#\">메뉴</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div id=\"lang\">\r\n");
      out.write("            <a href=\"#\">LOGIN</a>\r\n");
      out.write("            <span>&#124;</span>\r\n");
      out.write("            <a href=\"#\">JOIN</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <label class=\"menu_bg_close\" for=\"toggle_menu\"></label>\r\n");
      out.write("   </div><!--/toggle_nav-->\r\n");
      out.write("   \r\n");
      out.write("\t<!--BG, 임시예약 영역-->\r\n");
      out.write("\t<section id=\"mainSection\">\r\n");
      out.write("\t    <div class=\"bg\">\r\n");
      out.write("              <img class=\"pc\" src=\"img/img01.jpg\">\r\n");
      out.write("<!--               <img class=\"tablat\" src=\"img/img01_t.jpg\">\r\n");
      out.write("              <img class=\"mobile\" src=\"img/img01_m.jpg\"> \r\n");
      out.write("-->\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div id=\"booking\" class=\"section\">\r\n");
      out.write("\t\t<div class=\"section-center\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"booking-form\">\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"date\" class=\"row no-margin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6 fl-l\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"form-label\">대여일</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2020년</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>05/12</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>화요일</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>09:30</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6 fl-r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"form-label\">반납일</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2020년</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>05/16</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>토요일</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>14:30</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row no-margin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"form-label\">대여지점</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"select-arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"form-label\">반납지점</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>0</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"select-arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"form-label\">옵션</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"labelStyle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label><input type=\"checkbox\" value=\"01\">대형</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label><input type=\"checkbox\" value=\"01\">중형</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label><input type=\"checkbox\" value=\"01\">소형</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"form-label\">Email</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" placeholder=\"Enter your email\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"form-label\">Phone</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"tel\" placeholder=\"Enter your phone number\">\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"submit-btn\">Book Now</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--     \r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t메인페이지 콘센츠 영역\r\n");
      out.write("   <div id=\"contents_wrap\">    \r\n");
      out.write("       <section id=\"visual_image\">\r\n");
      out.write("            <div class=\"blind\">\r\n");
      out.write("                <h2>동아제약</h2>\r\n");
      out.write("                <h3>DONG-A PHARM</h3>\r\n");
      out.write("                <p>건강한 생활, 건강한 미래 동화제작이 함께 합니다</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"btn_view\">자세히 보기 </a>\r\n");
      out.write("       </section>\r\n");
      out.write("       \r\n");
      out.write("       <section id=\"product\">\r\n");
      out.write("            <h3>제품소개</h3>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <img src=\"images/produt_img.jpg\" alt=\"제품이미지\" />\r\n");
      out.write("            </figure>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"p1\"><a href=\"#\"><img src=\"images/produt_bacchusD.jpg\" alt=\"Bacchus-D\"></a></li>\r\n");
      out.write("                <li class=\"p2\"><a href=\"#\"><img src=\"images/produt_bacchusF.jpg\" alt=\"Bacchus-F\"></a></li>\r\n");
      out.write("                <li class=\"p3\"><a href=\"#\"><img src=\"images/produt_bacchusA.jpg\" alt=\"Bacchus DeCafe-a\"></a></li>\r\n");
      out.write("                <li class=\"p4\"><a href=\"#\"><img src=\"images/produt_benachio.jpg\" alt=\"베나치오\"></a></li>\r\n");
      out.write("                <li class=\"p5\"><a href=\"#\"><img src=\"images/produt_gagreen.jpg\" alt=\"가그린\"></a></li>\r\n");
      out.write("                <li class=\"p6\"><a href=\"#\"><img src=\"images/produt_ibong.jpg\" alt=\"아이봉\"></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("             <a href=\"#\" class=\"btn_view\">자세히 보기 </a>\r\n");
      out.write("       </section>\r\n");
      out.write("       \r\n");
      out.write("       <section id=\"social\">\r\n");
      out.write("            <h3>사회공헌</h3>\r\n");
      out.write("                <img class=\"pc\" src=\"images/visualImage.jpg\" alt=\"국토대장정 PC용 사진\">\r\n");
      out.write("                <img class=\"tablet\" src=\"images/visualImage_t.jpg\" alt=\"국토대장정 tabletpc용 사진\">\r\n");
      out.write("                <img class=\"mobile\" src=\"images/visualImage_m.jpg\" alt=\"국토대장정 mobile용 사진\">\r\n");
      out.write("           \r\n");
      out.write("       </section>\r\n");
      out.write("       \r\n");
      out.write("       <section id=\"history\">\r\n");
      out.write("            <h3>대학생 국토대장정</h3>\r\n");
      out.write("            <h2>동아제약 대학생 국토대장정</h2>\r\n");
      out.write("            <h1>역사관</h1>\r\n");
      out.write("            <p>동아제약 대학생 국토대장정의 오랜 역사를 한눈에 확인해보세요</p>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"poster\">\r\n");
      out.write("                <div class=\"imgs_wrap\">\r\n");
      out.write("                    <ul class=\"imgs\">\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/19.jpg\" alt=\"국토대장정 제19회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/18.jpg\" alt=\"국토대장정 제18회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/17.jpg\" alt=\"국토대장정 제17회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/16.jpg\" alt=\"국토대장정 제16회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/15.jpg\" alt=\"국토대장정 제15회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/14.jpg\" alt=\"국토대장정 제14회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/13.jpg\" alt=\"국토대장정 제13회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/12.jpg\" alt=\"국토대장정 제12회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/11.jpg\" alt=\"국토대장정 제11회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/10.jpg\" alt=\"국토대장정 제10회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/09.jpg\" alt=\"국토대장정 제9회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/08.jpg\" alt=\"국토대장정 제8회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/07.jpg\" alt=\"국토대장정 제7회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/06.jpg\" alt=\"국토대장정 제6회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/05.jpg\" alt=\"국토대장정 제5회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/04.jpg\" alt=\"국토대장정 제4회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/03.jpg\" alt=\"국토대장정 제3회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/02.jpg\" alt=\"국토대장정 제2회\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/01.jpg\" alt=\"국토대장정 제1회\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                    <div class=\"btn_prev\"></div>\r\n");
      out.write("                    <div class=\"btn_next\"></div>\r\n");
      out.write("            </div>/poster\r\n");
      out.write("       </section>\r\n");
      out.write("       <script>\r\n");
      out.write("\t   $(function(){\r\n");
      out.write("\t\t\tvar leftValue=0;\r\n");
      out.write("\t\t\t// .btn_next를 클릭했을때 \r\n");
      out.write("\t\t\t$(\"#poster > .btn_next\").click(function(){\r\n");
      out.write("\t\t\t//#poster > .imgs_wrap > ul.imgs 속성중 left값이 175 만큼 이동하도록\r\n");
      out.write("\t\t\t\tleftValue-=175;\r\n");
      out.write("\t\t\t\t$(\"#poster > .btn_prev\").css({background:\"url(images/btn_prev_a.png)\"});\r\n");
      out.write("\t\t\t//조건) 총 19개중 보여지는 이미지 갯수만큼 빼주고 x175, 왼쪽으로 이동시 - \r\n");
      out.write("\t\t\t\tvar maxLeft=$(\"#poster > .imgs_wrap > ul.imgs\").width()-$(\"#poster > .imgs_wrap\").width();\r\n");
      out.write("\t\t\t\tif(leftValue <= -maxLeft){\r\n");
      out.write("\t\t\t\t\tleftValue = -maxLeft;\r\n");
      out.write("\t\t\t\t\t$(\"#poster > .btn_next\").css({background:\"url(images/btn_next_n.png)\"});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#poster > .imgs_wrap > ul.imgs\").stop().animate({left:leftValue},500);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t// .btn_prev를 클릭했을때\r\n");
      out.write("\t\t\t$(\"#poster > .btn_prev\").click(function(){\r\n");
      out.write("\t\t\t// -175 만큼 이동하도록\r\n");
      out.write("\t\t\t\tleftValue+=175;\r\n");
      out.write("\t\t\t\t$(\"#poster > .btn_next\").css({background:\"url(images/btn_next_a.png)\"});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(leftValue >=0){\r\n");
      out.write("\t\t\t\t\tleftValue = 0;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#poster > .btn_prev\").css({background:\"url(images/btn_prev_n.png)\"});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#poster > .imgs_wrap > ul.imgs\").stop().animate({left:leftValue},500);\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t   </script>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("   </div>/contents_wrap\r\n");
      out.write("\r\n");
      out.write("\t푸터 영역   \r\n");
      out.write("   <footer id=\"main_footer\">\r\n");
      out.write("\t\t<div id=\"family_site\">\r\n");
      out.write("        \t<h3 class=\"f_title\">Family Site </h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>지주회사</dt>\r\n");
      out.write("                        <dd><a href=\"#\">동아쏘시오홀딩스</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>식음료</dt>\r\n");
      out.write("                        <dd><a href=\"#\">동아오츠카</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">동천수</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>제약</dt>\r\n");
      out.write("                        <dd><a href=\"#\">동아ST</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">동아제약</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">에스티팜</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">DMB</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>물류</dt>\r\n");
      out.write("                        <dd><a href=\"#\">용마로지스</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>병유리</dt>\r\n");
      out.write("                        <dd><a href=\"#\">수석</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>기계부품</dt>\r\n");
      out.write("                        <dd><a href=\"#\">한국신동공업</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>정보통신</dt>\r\n");
      out.write("                        <dd><a href=\"#\">DA인포메이션</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>건설</dt>\r\n");
      out.write("                        <dd><a href=\"#\">철근종합건설</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>해외</dt>\r\n");
      out.write("                        <dd><a href=\"#\">Dong-A America Co.</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">소주동아음료유한공사</a></dd>\r\n");
      out.write("                        <dd><a href=\"#\">Dong-A Participacoes Ltda</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div> \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"brand_site\">\r\n");
      out.write("        \t<h3 class=\"f_title\">Brand Site</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">가그린</a></li>\r\n");
      out.write("                <li><a href=\"#\">박카스</a></li>\r\n");
      out.write("                <li><a href=\"#\">모닝케어</a></li>\r\n");
      out.write("                <li><a href=\"#\">써큐란</a></li>\r\n");
      out.write("                <li><a href=\"#\">템포</a></li>\r\n");
      out.write("                <li><a href=\"#\">비겐크림톤</a></li>\r\n");
      out.write("                <li><a href=\"#\">국토대장정</a></li>\r\n");
      out.write("                <li><a href=\"#\">환경생명교실</a></li>\r\n");
      out.write("                <li><a href=\"#\">AD CAFE</a></li>\r\n");
      out.write("            </ul>            \r\n");
      out.write("        </div>  \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"policy\">\r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li><a href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("                <li class=\"last\"><a href=\"#\">인재개발원</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"f_address\">\r\n");
      out.write("            <h1 id=\"f_logo\"><img src=\"images/logo_footer.png\" alt=\"동아제약 로고\"/></h1>\r\n");
      out.write("            <address>\r\n");
      out.write("                <p>서울시 동대문구 천호대로 64 TEL.02 - 920 - 8112</p>\r\n");
      out.write("                <p class=\"copyright\">Copytight DONG-A PHARM. All rights reserved </p>\r\n");
      out.write("            </address>\r\n");
      out.write("            <div id=\"wa\"><a href=\"#\"><img src=\"images/award.jpg\" alt=\"WEB AWARD\"/></a></div>\r\n");
      out.write("   </footer>\r\n");
      out.write(" --></div><!--/wrap-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
