/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-09 12:06:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sist.com.dao.AppleDao;
import sist.com.model.BbsBean;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sist.com.dao.AppleDao");
    _jspx_imports_classes.add("sist.com.model.BbsBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>관리자</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<link href=\"../css/contents.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");

	int no = Integer.parseInt(request.getParameter("no"));
	String pageData = request.getParameter("page");
	BbsBean bean=(BbsBean)AppleDao.bbsInfo(no);
	String id=(String)request.getSession().getAttribute("id");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   function changeImge(obj){\r\n");
      out.write("\t   document.getElementById(\"ig\").src=obj.src;\r\n");
      out.write("   }\t   \r\n");
      out.write("   function deleteFun(obj){\r\n");
      out.write("\t   console.log(obj);\r\n");
      out.write("\t   console.log(obj.reply);\r\n");
      out.write("\t   if(obj.reply!=0){\r\n");
      out.write("\t\t   alert(\"댓글이 있으므로 삭제 할 수 없습니다.\");\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t\t   \r\n");
      out.write("\t   }\r\n");
      out.write("   }\r\n");
      out.write("\t  \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"topInfoWrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topInfoArea clfix\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"loginWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fir\">2012.05.17</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>13:30:22</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><em>");
      out.print(id );
      out.write("님</em> 좋은 하루 되세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" class=\"btnLogout\"><img src=\"../img/common/btn_logout.gif\" alt=\"로그아웃\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"gnbSubWrap\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<div id=\"contentsWrap\" class=\"contentsWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"title\">게시판 상세보기</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnSet clfix mgb15\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fr\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\"> <a href=\"password.jsp?no=");
      out.print(no);
      out.write("&job=modify&page=");
      out.print(request.getParameter("page") );
      out.write("\">수정</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(bean.getReply()==0){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"password.jsp?no=");
      out.print(no);
      out.write("&job=del&page=");
      out.print(request.getParameter("page"));
      out.write("&pnum=");
      out.print(bean.getPnum());
      out.write("\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								}else{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:deleteFun({no:");
      out.print(no);
      out.write(",job:'del',page:'");
      out.print(request.getParameter("page"));
      out.write("',reply:");
      out.print(bean.getReply());
      out.write(",pnum:");
      out.print(bean.getPnum());
      out.write("})\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\"><a href=\"edit.jsp?mode=reply&ref=");
      out.print(bean.getRef());
      out.write("&lev=");
      out.print(bean.getLev());
      out.write("&step=");
      out.print(bean.getStep());
      out.write("&pnum=");
      out.print(bean.getNo());
      out.write("\">답글</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 현재화면이 부모의 화면이므로 no의 값을 보내면  pNum의 값 -->\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\"><a href=\"list.jsp\">목록</a></span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsList\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"400\" />\r\n");
      out.write("                            <col width=\"100\" />\r\n");
      out.write("                            <col width=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\" class=\"fir\">이미지</th>\r\n");
      out.write("                             <th scope=\"col\">글번호</th>\r\n");
      out.write("                             <td>");
      out.print(bean.getNo() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        ");

                            String []res=bean.getFilename().split("#");
                        
      out.write(" \r\n");
      out.write("                          <td class=\"fir\" rowspan=\"7\"><img src=\"/web/upload/");
      out.print(res[0] );
      out.write("\" width=\"350\" height=\"330\" onmouseover=\"changeImge(this)\" id=\"ig\"/></td>\r\n");
      out.write("                          <th scope=\"col\">작성자</th>\t\r\n");
      out.write("                          <td>");
      out.print(bean.getWriter() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th scope=\"col\">제목</th>\r\n");
      out.write("                          <td>");
      out.print(bean.getTitle() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th scope=\"col\">내용</th>\r\n");
      out.write("                          <td height=\"200\">");
      out.print(bean.getContents() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th scope=\"col\">등록일</th>\r\n");
      out.write("                          <td>");
      out.print(bean.getRegdate() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th scope=\"col\">조회수</th>\r\n");
      out.write("                          <td>");
      out.print(bean.getHit() );
      out.write("</td>\r\n");
      out.write("                        </tr>                   \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table>\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t  <td>\r\n");
      out.write("\t\t\t\t\t    ");

					       for(int i=0;i<res.length;i++){
					    
      out.write("\r\n");
      out.write("\t\t\t\t\t    <img src=\"/web/upload/");
      out.print(res[i] );
      out.write("\" width=\"50\" height=\"50\"  onmouseover=\"changeImge(this)\"/>\r\n");
      out.write("\t\t\t\t\t    ");

					       }
					    
      out.write("\r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
