/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-13 05:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import sist.com.model.BbsBean;
import java.util.List;
import sist.com.dao.AppleDao;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("sist.com.dao.AppleDao");
    _jspx_imports_classes.add("sist.com.model.BbsBean");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>관리자</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<link href=\"../css/contents.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script>\r\n");
      out.write("   function searchData(){\r\n");
      out.write("\t   var obj=document.searchFrm;\r\n");
      out.write("\t   if(obj.query.value=='empty'|| !obj.data.value){\r\n");
      out.write("\t\t   alert('SearchData!');\r\n");
      out.write("\t\t   obj.query.selectedIndex=0;\r\n");
      out.write("\t\t   obj.data.value='';\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   obj.submit();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		List<BbsBean> list =null;
	    String query=request.getParameter("query");
	    String data=request.getParameter("data");
	    HashMap<String,Object>map=new HashMap<String,Object>();
	    if(query!=null&& data!=null){
        map.put("query", query);
        map.put("data", data);
		list=AppleDao.selectBbs(map);
	    }else{
	    	list=AppleDao.selectBbs(null);
	    }
	    
	
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"topInfoWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"topInfoArea clfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"loginWrap\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fir\">2012.05.17</span> <span>13:30:22</span> <span><em>OOO님</em>\r\n");
      out.write("\t\t\t\t\t\t\t좋은 하루 되세요</span> <a href=\"\" class=\"btnLogout\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../img/common/btn_logout.gif\" alt=\"로그아웃\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"gnbSubWrap\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<div id=\"contentsWrap\" class=\"contentsWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"title\">게시판 리스트</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnSet clfix mgb15\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fr\"> <span class=\"button\"><a href=\"javascript:searchData()\">검색</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\"><a href=\"edit.jsp\">글쓰기</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"button\"><a href=\"list.jsp\">새로고침</a></span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                   <form action=\"\" method=\"post\" name=\"searchFrm\">\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsWrite mgb35\">\r\n");
      out.write("\t\t\t\t\t\t<caption></caption>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>검색</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"query\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected=\"selected\" value=\"empty\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"TITLE\">TITLE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"WRITER\">WRITER</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"CONTENTS\">CONTENTS</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t <input type=\"text\" name=\"data\" class=\"inputText\" size=\"30\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsList\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"fir\">NO</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">IMAGE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">TITLE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">WRITER</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">HIT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">GRADE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">REGDATE</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (BbsBean b : list) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fir\">");
      out.print(b.getNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"hit.jsp?no=");
      out.print(b.getNo());
      out.write("&page=5\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"/web/upload/");
      out.print(b.getFilename());
      out.write("\" width=\"50\" height=\"50\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getTitle());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getHit());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										String img = "";
											switch (b.getGrade()) {
											case 1:
												img = "1.jpg";
												break;
											case 2:
												img = "2.jpg";
												break;
											case 3:
												img = "3.jpg";
												break;
											default:
												img = "4.jpg";
											}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/web/reImage/");
      out.print(img );
      out.write("\" width=\"50\" height=\"50\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getRegdate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"paging\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"../img/button/btn_first.gif\" alt=\"처음페이지\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"../img/button/btn_prev.gif\" alt=\"이전\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span> <a href=\"#\">1</a> <a href=\"#\">2</a> <a href=\"#\">3</a>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>4</strong> <a href=\"#\">5</a> <a href=\"#\">6</a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">7</a> <a href=\"#\">8</a> <a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t\t\t</span> <a href=\"#\"><img src=\"../img/button/btn_next.gif\" alt=\"다음\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"../img/button/btn_last.gif\" alt=\"마지막페이지\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
