/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-17 08:33:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.PORTFOLIO.team.var2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<title>SIST 렌트카</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basic.css\"/>\r\n");
      out.write("<body class=\"w3-light-grey\">\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation Bar -->\r\n");
      out.write("<div class=\"w3-bar w3-white w3-large\" id=\"nav\">\r\n");
      out.write("  <a href=\"index.jsp\" class=\"w3-bar-item w3-button w3-red w3-mobile\"><i class=\"fa fa-bed w3-margin-right\"></i>SIST RENTCAR</a>\r\n");
      out.write("  <a href=\"#rooms\" class=\"w3-bar-item w3-button w3-mobile\">예약</a>\r\n");
      out.write("  <a href=\"#about\" class=\"w3-bar-item w3-button w3-mobile\">게시판</a>\r\n");
      out.write("  <a href=\"#contact\" class=\"w3-bar-item w3-button w3-mobile\">마이페이지</a>\r\n");
      out.write("  <a href=\"#contact\" class=\"w3-bar-item w3-button w3-right w3-light-grey w3-mobile\">회원가입</a>\r\n");
      out.write("  <a href=\"#contact\" class=\"w3-bar-item w3-button w3-right w3-light-grey w3-mobile\">로그인</a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"w3-display-container w3-content\" style=\"max-width:1500px;\">\r\n");
      out.write("  <img class=\"w3-image\" src=\"image/bg.jpg\" alt=\"배경화면\" style=\"min-width:1000px\" width=\"1500\" height=\"800\">\r\n");
      out.write("  <div class=\"w3-display-left w3-padding w3-col l6 m8\">\r\n");
      out.write("    <div class=\"w3-container w3-red\">\r\n");
      out.write("      <h2><i class=\"fa fa-bed w3-margin-right\"></i>SIST RENTCAR</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-container w3-white w3-padding-16\">\r\n");
      out.write("      <form action=\"/action_page.php\" target=\"_blank\">\r\n");
      out.write("        <div class=\"w3-row-padding\" style=\"margin:0 -16px;\">\r\n");
      out.write("          <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("            <label><i class=\"fa fa-calendar-o\"></i>대여일</label>\r\n");
      out.write("            <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"YYYY/MM/DD\" name=\"CheckIn\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"w3-half\">\r\n");
      out.write("            <label><i class=\"fa fa-calendar-o\"></i> 반납일</label>\r\n");
      out.write("            <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"YYYY/MM/DD\" name=\"CheckOut\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-row-padding\" style=\"margin:8px -16px;\">\r\n");
      out.write("          <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("            <label><i class=\"fa fa-male\"></i>대여지점</label>\r\n");
      out.write("            <!-- <input type=\"number\" value=\"1\" name=\"Adults\" min=\"1\" max=\"6\"> -->\r\n");
      out.write("          \t<select  class=\"w3-input w3-border\" id=\"place\" name=\"place\">\r\n");
      out.write("\t\t\t  <option value=\"강남지점\">강남지점</option>\r\n");
      out.write("\t\t\t  <option value=\"관악지점\">관악지점</option>\r\n");
      out.write("\t\t\t  <option value=\"구로지점\">구로지점</option>\r\n");
      out.write("\t\t\t  <option value=\"여의도지점\">여의도지점</option>\r\n");
      out.write("\t\t\t  <option value=\"홍대지점\">홍대지점</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"w3-half\">\r\n");
      out.write("            <label><i class=\"fa fa-child\"></i>인원수</label>\r\n");
      out.write("          <input class=\"w3-input w3-border\" type=\"number\" value=\"0\" name=\"Kids\" min=\"0\" max=\"6\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"w3-button w3-dark-grey\" type=\"submit\"><i class=\"fa fa-search w3-margin-right\"></i>예약하기</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page content -->\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:1532px;\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container w3-margin-top\" id=\"rooms\">\r\n");
      out.write("    <h3>Rooms</h3>\r\n");
      out.write("    <p>Make yourself at home is our slogan. We offer the best beds in the industry. Sleep well and rest well.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding\">\r\n");
      out.write("    <div class=\"w3-col m3\">\r\n");
      out.write("      <label><i class=\"fa fa-calendar-o\"></i> Check In</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"DD MM YYYY\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m3\">\r\n");
      out.write("      <label><i class=\"fa fa-calendar-o\"></i> Check Out</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"DD MM YYYY\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-male\"></i> Adults</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" placeholder=\"1\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-child\"></i> Kids</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" placeholder=\"0\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-search\"></i> Search</label>\r\n");
      out.write("      <button class=\"w3-button w3-block w3-black\">Search</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-row-padding w3-padding-16\">\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"image/room_single.jpg\" alt=\"Norway\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>Single Room</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $99</h6>\r\n");
      out.write("        <p>Single bed</p>\r\n");
      out.write("        <p>15m<sup>2</sup></p>\r\n");
      out.write("        <p class=\"w3-large\"><i class=\"fa fa-bath\"></i> <i class=\"fa fa-phone\"></i> <i class=\"fa fa-wifi\"></i></p>\r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">Choose Room</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"image/room_double.jpg\" alt=\"Norway\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>Double Room</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $149</h6>\r\n");
      out.write("        <p>Queen-size bed</p>\r\n");
      out.write("        <p>25m<sup>2</sup></p>\r\n");
      out.write("        <p class=\"w3-large\"><i class=\"fa fa-bath\"></i> <i class=\"fa fa-phone\"></i> <i class=\"fa fa-wifi\"></i> <i class=\"fa fa-tv\"></i></p>\r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">Choose Room</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"image/room_deluxe.jpg\" alt=\"Norway\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>Deluxe Room</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $199</h6>\r\n");
      out.write("        <p>King-size bed</p>\r\n");
      out.write("        <p>40m<sup>2</sup></p>\r\n");
      out.write("        <p class=\"w3-large\"><i class=\"fa fa-bath\"></i> <i class=\"fa fa-phone\"></i> <i class=\"fa fa-wifi\"></i> <i class=\"fa fa-tv\"></i> <i class=\"fa fa-glass\"></i> <i class=\"fa fa-cutlery\"></i></p>\r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">Choose Room</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-row-padding\" id=\"about\">\r\n");
      out.write("    <div class=\"w3-col l4 12\">\r\n");
      out.write("      <h3>About</h3>\r\n");
      out.write("      <h6>Our hotel is one of a kind. It is truely amazing. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</h6>\r\n");
      out.write("    <p>We accept: <i class=\"fa fa-credit-card w3-large\"></i> <i class=\"fa fa-cc-mastercard w3-large\"></i> <i class=\"fa fa-cc-amex w3-large\"></i> <i class=\"fa fa-cc-cc-visa w3-large\"></i><i class=\"fa fa-cc-paypal w3-large\"></i></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l8 12\">\r\n");
      out.write("      <!-- Image of location/map -->\r\n");
      out.write("      <img src=\"image/map.jpg\" class=\"w3-image w3-greyscale\" style=\"width:100%;\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding w3-large w3-center\" style=\"margin:32px 0\">\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-map-marker w3-text-red\"></i> 423 Some adr, Chicago, US</div>\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-phone w3-text-red\"></i> Phone: +00 151515</div>\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-envelope w3-text-red\"></i> Email: mail@mail.com</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-panel w3-red w3-leftbar w3-padding-32\">\r\n");
      out.write("    <h6><i class=\"fa fa-info w3-deep-orange w3-padding w3-margin-right\"></i> On demand, we can offer playstation, babycall, children care, dog equipment, etc.</h6>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("    <h3>Our Hotels</h3>\r\n");
      out.write("    <h6>You can find our hotels anywhere in the world:</h6>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding w3-padding-16 w3-text-white w3-large\">\r\n");
      out.write("    <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("      <div class=\"w3-display-container\">\r\n");
      out.write("        <img src=\"image/cinqueterre.jpg\" alt=\"Cinque Terre\" style=\"width:100%\">\r\n");
      out.write("        <span class=\"w3-display-bottomleft w3-padding\">Cinque Terre</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-half\">\r\n");
      out.write("      <div class=\"w3-row-padding\" style=\"margin:0 -16px\">\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"image/newyork2.jpg\" alt=\"New York\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">New York</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"image/sanfran.jpg\" alt=\"San Francisco\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">San Francisco</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-row-padding\" style=\"margin:0 -16px\">\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"image/pisa.jpg\" alt=\"Pisa\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">Pisa</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"image/paris.jpg\" alt=\"Paris\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">Paris</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container w3-padding-32 w3-black w3-opacity w3-card w3-hover-opacity-off\" style=\"margin:32px 0;\">\r\n");
      out.write("    <h2>Get the best offers first!</h2>\r\n");
      out.write("    <p>Join our newsletter.</p>\r\n");
      out.write("    <label>E-mail</label>\r\n");
      out.write("    <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Your Email address\">\r\n");
      out.write("    <button type=\"button\" class=\"w3-button w3-red w3-margin-top\">Subscribe</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container\" id=\"contact\">\r\n");
      out.write("    <h2>Contact</h2>\r\n");
      out.write("    <p>If you have any questions, do not hesitate to ask them.</p>\r\n");
      out.write("    <i class=\"fa fa-map-marker w3-text-red\" style=\"width:30px\"></i> Chicago, US<br>\r\n");
      out.write("    <i class=\"fa fa-phone w3-text-red\" style=\"width:30px\"></i> Phone: +00 151515<br>\r\n");
      out.write("    <i class=\"fa fa-envelope w3-text-red\" style=\"width:30px\"> </i> Email: mail@mail.com<br>\r\n");
      out.write("    <form action=\"/action_page.php\" target=\"_blank\">\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Name\" required name=\"Name\"></p>\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Email\" required name=\"Email\"></p>\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Message\" required name=\"Message\"></p>\r\n");
      out.write("      <p><button class=\"w3-button w3-black w3-padding-large\" type=\"submit\">SEND MESSAGE</button></p>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<!-- End page content -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-padding-32 w3-black w3-center w3-margin-top\">\r\n");
      out.write("  <h5>Find Us On</h5>\r\n");
      out.write("  <div class=\"w3-xlarge w3-padding-16\">\r\n");
      out.write("    <i class=\"fa fa-facebook-official w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-instagram w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-snapchat w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-pinterest-p w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-twitter w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-linkedin w3-hover-opacity\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\" class=\"w3-hover-text-green\">w3.css</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
