/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-15 10:41:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.PORTFOLIO.dongwha.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>기업소개</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/master.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/introduction.css\" media=\"screen and (min-width: 1367px)\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/introduction_tablet_mobile.css\" media=\"screen and (max-width: 1367px)\" />\r\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<input id=\"toggle_menu\" type=\"checkbox\" />\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("    \r\n");
      out.write("\t\t<div class=\"skip\">\r\n");
      out.write("\t\t\t<a href=\"#main_nav\">메인메뉴 바로가기</a>\r\n");
      out.write("\t\t\t<a href=\"#contents_wrap\">본문 바로가기</a>\r\n");
      out.write("\t\t\t<a href=\"#main_footer\">푸터 바로가기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("        <header id=\"main_header\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<!--로고-->\r\n");
      out.write("\t\t\t\t<h1 id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\">동화제약</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--언어선택 웹-->\r\n");
      out.write("\t\t\t\t<nav id=\"lang_web\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"choice\">KO</a>\r\n");
      out.write("\t\t\t\t\t<span>|</span>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">EN</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("                    \r\n");
      out.write("                    $(function(){\r\n");
      out.write("                        setInterval(function(){\r\n");
      out.write("                            if($(window).scrollTop()>=110){\r\n");
      out.write("                               $(\"#main_header\").addClass(\"scroll\");\r\n");
      out.write("                            }else{\r\n");
      out.write("                               $(\"#main_header\").removeClass(\"scroll\");\r\n");
      out.write("                            }\r\n");
      out.write("                        },1000);\r\n");
      out.write("                    });\r\n");
      out.write("                </script>                \r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<!--메인메뉴-->\r\n");
      out.write("                <script>\r\n");
      out.write("\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\tvar mainNavAry=[false, false, false, false, false, false, false];\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_nav > div > ul > li\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\tvar index=$(this).index();\r\n");
      out.write("\t\t\t\t\t\t\tmainNavAry[index]=!mainNavAry[index];\r\n");
      out.write("\t\t\t\t\t\t\tif(mainNavAry[index]){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).removeClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("                </script>\r\n");
      out.write("\t\t\t\t<label class=\"menu\" for=\"toggle_menu\">메인메뉴</label>\r\n");
      out.write("\t\t\t\t<nav id=\"main_nav\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!--언어선택 모바일-->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"navtop_m\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"choice\">KO</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>|</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">EN</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"menu_close\" for=\"toggle_menu\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div><!--#navtop_m-->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>소개</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">기업소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">CEO인사말</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">연혁</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사가</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">동화 브로슈어</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">CI</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">연구소/공장</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">가족친화우수기업</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사회공헌</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">가족회사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">채용</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>채용</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">인재상</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">인사제도</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">복리후생</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">채용안내</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">상시채용</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">지원결과 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">자주하는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">채용 Q&#38;A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">IR자료실</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>IR자료실</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">공시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사업보고서</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">전자공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">연구</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>연구</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">R&D 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">R&D 뉴스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">주요 연구실적</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">조직 및 업무</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">신약개발 주력분야</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">주요 연구과제</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">기술혁신 네트워크</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">글로벌 동화</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">제품</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>제품</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">제품 공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">신제품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">전문의약품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">일반의약품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">의약외품ㆍ의료기기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">건강기능식품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">식품ㆍ음료</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">화장품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">미디어</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>미디어</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">동화뉴스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">광고갤러리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">뉴스레터</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">동화캐릭터</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">자율준수</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>자율준수</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">자율준수 관리자</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">자율준수 프로그램</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">조직 및 운영</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">관련사이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사이버 제보센터</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav><!--//#main_nav-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("\t\t<section id=\"banner\">\r\n");
      out.write("\t\t\t<h3>\r\n");
      out.write("\t\t\t\t좋은약이 아니면 만들지 마라.<br />\r\n");
      out.write("\t\t\t\t동화는 동화식구 모두의 것이니 온 식구가 정성을 다해 다 같이 잘 살 수 있는 기업으로 이끌어라.\"<br />\r\n");
      out.write("\t\t\t\t5대사장 보당 윤창식\"\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!--footer-->\r\n");
      out.write("        <footer id=\"main_footer\">\r\n");
      out.write("            <div id=\"logo_web\"><!--웹용-->\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li><a href=\"#\"><img src=\"images/logo_bestfamily.png\" alt=\"가족친화 우수기업\"/></a></li>\r\n");
      out.write("                \t<li><a href=\"#\"><img src=\"images/logo_CP.png\" alt=\"공정거래 자율준수 프로그램 AA등급\"/></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"images/logo_ISO.png\" alt=\"ISO 9001(품질경영) 및 1SO 14001(환경경영) 인증\"/></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"images/logo_whalmyungsu.jpg\" alt=\"활명수\"/></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"images/logo_each.jpg\" alt=\"잇치\"/></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"images/logo_fucidin.jpg\" alt=\"후시딘\"/></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img calss=\"last\" src=\"images/logo_intrinsic.jpg\" alt=\"인트린직\"/></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div><!--#logo_web-->\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"gotop\">TOP</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\tvar bCheck = false;\r\n");
      out.write("\t\t\t\t\t$(\"#fms_m > div\").click(function(){\r\n");
      out.write("\t\t\t\t\t\tbCheck = !bCheck;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(bCheck == true){ \r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$(this).removeClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("            \t\r\n");
      out.write("\t\t\t<div id=\"fms_m\"><!--모바일용-->\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h2>패밀리사이트 바로가기</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">활명수</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">잇치</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">후시딘</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">인트린직</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!--#fms_m-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("                <div id=\"f_address\">\r\n");
      out.write("                \t\r\n");
      out.write("                    <address>\r\n");
      out.write("                        <div id=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>04637 서울특별시 중구 후암로 98 (남대문로5가 631), LG서울역빌딩 19층 </p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>대표이사 : 윤도준, 유광렬</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tel\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Tel : 02-2021-9300</p>  \r\n");
      out.write("\t\t\t\t\t\t\t<span>|</span> \r\n");
      out.write("\t\t\t\t\t\t\t<p>Fax : 02-776-7873</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>|</span> \r\n");
      out.write("\t\t\t\t\t\t\t<p>Mail : dongwha@dong-wha.co.kr</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</address>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/footer_instar.png\" alt=\"인스타그램 바로가기\" /></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/footer_youtube.png\" alt=\"유투브 바로가기\" /></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><img src=\"images/footer_facebook.png\" alt=\"페이스북 바로가기\" /></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    <p>Copyright(c) DONG WHA PHARM. CO., LTD.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("        </footer>        \r\n");
      out.write(" \t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
